current_dir := ${CURDIR}
TOP := simpleCounter
TARGET := basys3
SOURCES := ${current_dir}/simpleCounter.sv
TMR_SCRIPT := ${current_dir}/tmr_script.py

export TMR_SCRIPT
export CONSTRAINT_NEW

XDC := ${current_dir}/simpleCounter.xdc
CONSTRAINT_NEW := ${current_dir}/new_constraints.txt

include common.mk