language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install ply
  - pip install git+https://github.com/byuccl/spydrnet.git
  - pip install pylint
script:
  - pytest
