language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
  - "3.9"
branches:
  only: 
    - master
install:
  - pip install ply
  - pip install spydrnet
  - pip install networkx
script:
  - pytest
