my_project_settings:
  replication:
    instances_to_replicate:
      all
    ports_to_replicate:
      top_level_input_ports
  voter_insertion:
    reduction:
      instances_at_valid_points:
        all
      ports_at_valid_points:
        all