current_dir := ${CURDIR}
TOP := top_pong
TARGET := basys3
SOURCES := ${current_dir}/*v 
TMR_SCRIPT := ${current_dir}/tmr_script.py

XDC := ${current_dir}/pong.xdc
CONSTRAINT_NEW := ${current_dir}/new_constraints.txt

export TMR_SCRIPT
export CONSTRAINT_NEW

include common.mk