replication:
  # Here is an example of excluding an instance within the design. The 
  # hierarchical name is required.
  instances_to_replicate:
    exclude_hinst: ["PURPOSEFUL_GENERATE[8].SEQUENTIAL_LOGIC/DQ_reg[1]"]
  ports_to_replicate:
    all
voter_insertion:
  reduction:
    # Here is an example of excluding all instances of a primitive type for
    # voter insertion. In this case, we want to do this because the flip-flop
    # that is excluded from replication will receive a clock signal from the
    # global clock buffer, and we don't want to place a voter in its path, so
    # we'll exclude all BUFGs from the reduction voter insertion algorithm.
    instances_at_valid_points:
      exclude_prim: ["BUFG"]
    ports_at_valid_points:
      all